version: '3.8'

services:
 # temperature_feed:
 #   build: .
 #   ports:
 #     - "8000:8000"

  timeseries_temperature_db:
    image: influxdb:latest
    container_name: timeseries_temperature_db
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb_data:/root/.influxdbv2  # Volume for persisting InfluxDB data
    environment:
      - INFLUXDB_DB=temperature
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-admin-token
    restart: always
    ports:
      - "8086:8086"

  
  satellite-temperature:
    image: us.gcr.io/loft-orbital-public/hiring/challenges/ground-software/back-end/satellite-temperature
    container_name: satellite-temperature
    ports:
      - "1000:4000"


volumes:
    influxdb_data:  # Define the volume for InfluxDB data persistence
