# Generated by Django 3.2.20 on 2023-07-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperaturemeasurementmodel',
            options={'managed': False},
        ),
    ]
